---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# bbousims

<!-- badges: start -->
<!-- badges: end -->

The goal of bbousims is to ...

## Installation

You can install the development version of bbousims from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("poissonconsulting/bbousims")
```

## Simulate Boreal Caribou survival and recruitment data

### Get demographic summary from key parameters

## Doing more with `bbousims`
`bbousims` contains more flexible functionality to work with any stage composition.
For example, given the following stage composition

### Generate survival and fecundity rates

### Process matrix multiplication with demographic stochasticity

We defined the custom infix operator `%*b%` to perform matrix multiplication with stochasticity. Instead of multiplying the population at each stage by the corresponding rate, `%*b%` draws from a binomial distribution, where size is the population and probability is the rate of interest.  

For example, with population vector and survival process matrix

regular (deterministic) matrix multiplication yields

Stochastic matrix multiplication yields 

where the resulting population is composed of whole individuals and each iteration is different.  

### Simulate population projection from BAS model

### Simulate observed composition groups